### ISSUE TITLE
Create "Timesheets" endpoint

### ISSUE THREAD

**Issue by mihikaiyer** [Code-4-Community/breaktime-backend#3]
Create a get timesheets endpoint:
`GET api/v1/protected/timesheets`

Authentication token should also be sent into header.

This will be a list of TimeSheet objects to query from 

Response body:
```json 
{
   "StartDate-of-TimeSheet": 
   {
     "UUID":"Unique Table ID",
       "StartDate": "Epoch", 
        "Status":"Status of timesheet", 
        "Company": "Company Name" 
   }
}
```

Bad response:
Error code 400 if invalid dates are provided 

Unauthorized response:
Error code 401 if user ID does not match calling user ID (unless its an admin) or does not exist (unless its an admin in which case would throw bad response instead)

**Comment by izzyconner** [comment]
Clock in/out can be in 24-hour time format

**Comment by izzyconner** [comment]
Leaving this in blocked until Stephen, Kaylee, and I get more of the backend properly set up with AWS, then will resume work. For now, pivoting to front end
